# =============================================================================
# Fenexity MicroOCPP Simulator - Depot Docker Compose
# =============================================================================
# Automatisch generiert aus Depot CSV
# OCPP Version: 1.6
# Generiert am: 2025-09-23 18:45:33
# =============================================================================

version: '3.8'

networks:
  fenexity-csms:
    external: true

services:
  depot-config:
    image: alpine:latest
    container_name: depot-multi-config
    command: >
      sh -c "
        echo '🔧 Starting Depot Multi-Container Configuration...'
        echo '📊 OCPP Version: 1.6'
        echo '📈 Total Simulators:        3'
        echo '🎯 Configuration completed successfully!'
        sleep 5
      "
    networks:
      - fenexity-csms

  sim-RESTART-001:
    image: microocpp-sim-v16:latest
    container_name: sim-RESTART-001
    platform: linux/arm64
    ports:
      - "7101:8000"
    volumes:
      - "./mo_store_depot/depot_v16_001:/MicroOcppSimulator/mo_store:rw"
      - "./config:/MicroOcppSimulator/config:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - fenexity-csms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - depot-config
    environment:
      - OCPP_VERSION=1.6
      - CHARGER_ID=RESTART-001
      - SIMULATOR_PORT=8000
      - API_PORT=7101
      - MO_ENABLE_V201=0

  sim-RESTART-002:
    image: microocpp-sim-v16:latest
    container_name: sim-RESTART-002
    platform: linux/arm64
    ports:
      - "7102:8000"
    volumes:
      - "./mo_store_depot/depot_v16_002:/MicroOcppSimulator/mo_store:rw"
      - "./config:/MicroOcppSimulator/config:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - fenexity-csms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - depot-config
    environment:
      - OCPP_VERSION=1.6
      - CHARGER_ID=RESTART-002
      - SIMULATOR_PORT=8000
      - API_PORT=7102
      - MO_ENABLE_V201=0

  sim-RESTART-003:
    image: microocpp-sim-v16:latest
    container_name: sim-RESTART-003
    platform: linux/arm64
    ports:
      - "7103:8000"
    volumes:
      - "./mo_store_depot/depot_v16_003:/MicroOcppSimulator/mo_store:rw"
      - "./config:/MicroOcppSimulator/config:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - fenexity-csms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - depot-config
    environment:
      - OCPP_VERSION=1.6
      - CHARGER_ID=RESTART-003
      - SIMULATOR_PORT=8000
      - API_PORT=7103
      - MO_ENABLE_V201=0

